main=$(gum style --foreground 212 'bat')
gum join "Applyed" " $main" ": $(dirname $(readlink -f "$0"))"

alias cat="bat --paging=never --plain"
help() {
    "$@" --help 2>&1 | bat --paging=never --plain -l=help
}
